.\" manpageeditorqt
.TH "manpageeditorqt" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
manpageeditorqt \- manual page for manpageeditorqt 0.0.0
.SH "SYNOPSIS"
.B manpageeditorqt
.SH "DESCRIPTION"
A GUI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
manpageeditorqt
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
