.TH "myprogram" "1" "0.0.0" "Me" "My set of programs"
.SH "NAME"
myprogram - Does some neat things
.br
.SH "SYNTAX"
myprogram [\fIoption\fR] <\fIfilename\fR>
.br
myprogram \fI-dscan\fR <\fIdirectory\fR>
.br
.SH "DESCRIPTION"
This program does some very neat things.
.br
.SH "OPTIONS"
\fB-dscan \fR<\fIdirectory\fR>
.br
		Scans specified <\fIdirectory\fR>.
.br

\fB--help\fR
.br
		Output help information and exit.
.br

\fB--version\fR
.br
		Output version information and exit.
.br
.SH "FILES"
\fI/etc/myprogram\fR
.br
\fI/var/log\fR
.br
.SH "ENVIRONMENT VARIABLES"
\fBHOME\fR
.br
		Specifies the home directory
.br

\fBLOGINNAME\fR
.br
		Specifies the user's login name
.br

\fBPRINTER\fR
.br
		Specifies the printer
.br
.SH "EXAMPLES"
To run this program the standard way type:
.br

myprogram /tmp/myfile
.br

Alternatively you can run it as:
.br

myprogram -dscan /tmp
.br
.SH "AUTHORS"
me <me@myhost.org>
.br
.SH "SEE ALSO"
myotherprogram(2) mynextprogram(2)
.br
